#!/bin/bash
# Runs the whole measurement suite on a dedicated machine (meant for a VM with nothing else on it)
# and packs the results with a description of the environment.
#
#   1. correctness: sequential and concurrent load on Netty NIO, Netty epoll and CIO, agent on
#   2. closed-loop overhead: run_overhead.sh, agent off / on, ROUNDS rounds in alternating order
#   3. open-loop saturation: fixed arrival rates, agent off / on, JVM CPU per request
#
# Usage: vm/measure.sh [results-name]      (results land in demo/<results-name>, default results-vm-<time>)
# Env:   ROUNDS=5 REQUESTS=4000 CONCURRENCY=16 WARMUP=300
#        RATES="300 600 900 1200 1500" DURATION=20 STEP_GAP=60 (seconds between open-loop steps)
#        PIN=auto|0|1   split CPUs between frontend, backend/jaeger and the load generator
#        SKIP=correctness,overhead,openloop   comma-separated phases to skip
set -u
cd "$(dirname "$0")/.."
NAME=${1:-results-vm-$(date +%Y%m%d-%H%M%S)}
OUT=demo/$NAME
ROUNDS=${ROUNDS:-5}
RATES=${RATES:-300 600 900 1200 1500}
LOADGEN_IMAGE=${LOADGEN_IMAGE:-python:3.12-slim}
DURATION=${DURATION:-20}
STEP_GAP=${STEP_GAP:-60}
SKIP=${SKIP:-}
export REQUESTS=${REQUESTS:-4000} CONCURRENCY=${CONCURRENCY:-16} WARMUP=${WARMUP:-300}
AGENT="-javaagent:/coroagent/coroagent.jar -Dobicoro.native=/coroagent/libcoroagent.so"
mkdir -p "$OUT"
log() { echo "[measure $(date +%H:%M:%S)] $*" | tee -a "$OUT/measure.log"; }
skipped() { [[ ",$SKIP," == *",$1,"* ]]; }

# ---- CPU pinning and network limits ---------------------------------------------------------
# Every request opens a new connection (loadgen -> frontend, frontend -> backend), and a closed
# connection holds its source port in TIME_WAIT for 60 s. With the default 28k-port range that
# caps sustained new connections to one destination near 470/s, below the rates the open-loop
# sweep tries. Widen the range and allow TIME_WAIT reuse, in the frontend's network namespace
# and on this machine (restored on exit).
N=$(nproc)
PIN=${PIN:-auto}
[ "$PIN" = auto ] && { [ "$N" -ge 8 ] && PIN=1 || PIN=0; }
LOAD_CPUS=0-$((N - 1)); LOAD_PROCS=$N
FRONT_CPUS=; BACK_CPUS=
if [ "$PIN" = 1 ]; then
    F=$((N / 2)); B=$((N / 4))
    FRONT_CPUS=0-$((F - 1)); BACK_CPUS=$F-$((F + B - 1)); LOAD_CPUS=$((F + B))-$((N - 1)); LOAD_PROCS=$((N - F - B))
    log "pinning: frontend $FRONT_CPUS, backend/jaeger/obi $BACK_CPUS, load generator $LOAD_CPUS (of $N)"
else
    log "pinning off ($N CPUs)"
fi
{
    echo "# Generated by vm/measure.sh."
    echo "services:"
    echo "  frontend:"
    [ -n "$FRONT_CPUS" ] && echo "    cpuset: \"$FRONT_CPUS\""
    echo "    sysctls:"
    echo "      net.ipv4.ip_local_port_range: \"1024 65535\""
    echo "      net.ipv4.tcp_tw_reuse: \"1\""
    if [ -n "$BACK_CPUS" ]; then
        for svc in backend jfront jaeger obi; do printf '  %s:\n    cpuset: "%s"\n' "$svc" "$BACK_CPUS"; done
    fi
} > demo/docker-compose.pin.yml
export COMPOSE_FILE=docker-compose.yml:docker-compose.pin.yml
OLD_PORT_RANGE=$(sysctl -n net.ipv4.ip_local_port_range | tr -s '\t ' ' ')
OLD_TW_REUSE=$(sysctl -n net.ipv4.tcp_tw_reuse)
sudo sysctl -q -w net.ipv4.ip_local_port_range="1024 65535" net.ipv4.tcp_tw_reuse=1
restore_sysctls() {
    sudo sysctl -q -w net.ipv4.ip_local_port_range="$OLD_PORT_RANGE" net.ipv4.tcp_tw_reuse="$OLD_TW_REUSE"
}
trap restore_sysctls EXIT
LOAD="taskset -c $LOAD_CPUS"

# ---- environment ----------------------------------------------------------------------------
{
    echo "# measure.sh run $NAME"
    echo "date: $(date -Is)"; echo "git: $(git rev-parse --short HEAD) $(git status --porcelain | wc -l) dirty files"
    echo "kernel: $(uname -r)"; echo "btf: $(ls /sys/kernel/btf/vmlinux 2>&1)"
    echo "cpus: $N, pin=$PIN load=$LOAD_CPUS ($LOAD_PROCS loadgen processes)"
    echo "sysctl during run: ip_local_port_range=1024-65535 tcp_tw_reuse=1 (was $OLD_PORT_RANGE / $OLD_TW_REUSE)"; lscpu | grep -E 'Model name|Hypervisor|Thread|Core|Socket|MHz' || true
    free -h | head -2
    echo "docker: $(docker --version 2>&1)"; echo "java: $(java -version 2>&1 | head -1)"
    echo "bpftrace: $(${BPFTRACE:-bpftrace} --version 2>&1)"
    echo "load average at start: $(cat /proc/loadavg)"
    echo "busiest processes at start:"; top -b -n1 -o %CPU | sed -n 7,12p
    echo "config: ROUNDS=$ROUNDS REQUESTS=$REQUESTS CONCURRENCY=$CONCURRENCY WARMUP=$WARMUP RATES=\"$RATES\" DURATION=$DURATION"
} > "$OUT/env.txt"

compose() { (cd demo && sudo -E docker compose "$@"); }
up() {  # <java opts> [extra env assignments...]; aborts the run if the stack does not serve
    local opts=$1; shift
    compose down >> "$OUT/measure.log" 2>&1
    if ! (cd demo && env "$@" FRONTEND_JAVA_OPTS="$opts" sudo -E docker compose up -d) >> "$OUT/measure.log" 2>&1; then
        log "FATAL: docker compose up failed (see above)"; exit 1
    fi
    sleep 25
    for _ in 1 2 3; do for ep in direct hop parallel; do curl -s -m 10 -o /dev/null "http://localhost:8080/$ep"; done; done
    if [ "$(curl -s -m 10 -o /dev/null -w '%{http_code}' http://localhost:8080/direct)" != 200 ]; then
        log "FATAL: frontend does not answer /direct with 200"; compose logs --no-color --tail 50 >> "$OUT/measure.log" 2>&1; exit 1
    fi
    sleep 5
}
step() {  # <name> <command...>: runs a helper, keeps its output in the log, reports failures
    local name=$1; shift
    "$@" >> "$OUT/measure.log" 2>&1 || log "WARNING: $name exited with $?"
}
frontend_pid() { (cd demo && sudo docker inspect -f '{{.State.Pid}}' "$(sudo docker compose ps -q frontend)"); }
cpu_ticks() { sudo awk '{ sub(/^.*\) /, ""); print $12 + $13 }' "/proc/$1/stat"; }
# "steal total" jiffies of this machine: steal is time the hypervisor gave our vCPUs to others.
steal_total() { awk '/^cpu / { t = 0; for (i = 2; i <= NF; i++) t += $i; print $9, t }' /proc/stat; }
# ListenOverflows ListenDrops of a process's network namespace (the frontend container).
listen_drops() {
    sudo cat "/proc/$1/net/netstat" | awk '/^TcpExt:/ { if (!n) { for (i = 2; i <= NF; i++) k[i] = $i; n = 1 }
        else { for (i = 2; i <= NF; i++) v[k[i]] = $i; print v["ListenOverflows"] + 0, v["ListenDrops"] + 0 } }'
}

# ---- 1. correctness -------------------------------------------------------------------------
if ! skipped correctness; then
    for variant in nio epoll cio; do
        case $variant in nio) extra=();; epoll) extra=(NETTY_TRANSPORT=epoll);; cio) extra=(KTOR_ENGINE=cio);; esac
        log "correctness: $variant"
        up "$AGENT" "${extra[@]}"
        mkdir -p "$OUT/seq-$variant" "$OUT/conc-$variant"
        step "run_conditions ($variant)" $LOAD demo/run_conditions.sh "$NAME/seq-$variant"
        python3 demo/analyze_jaeger.py "$NAME/seq-$variant" > "$OUT/seq-$variant/analysis.txt" 2>> "$OUT/measure.log"
        step "run_concurrent ($variant)" $LOAD demo/run_concurrent.sh "$NAME/conc-$variant"
        python3 demo/analyze_concurrent.py "$NAME/conc-$variant" > "$OUT/conc-$variant/analysis.txt" 2>> "$OUT/measure.log"
        compose logs --no-color frontend 2>&1 | grep -c 'transform error' | sed 's/^/transform errors: /' >> "$OUT/conc-$variant/analysis.txt"
    done
fi

# ---- 2. closed-loop overhead ----------------------------------------------------------------
if ! skipped overhead; then
    for r in $(seq 1 "$ROUNDS"); do
        order="agent-off agent-on"; [ $((r % 2)) = 0 ] && order="agent-on agent-off"
        for label in $order; do
            log "overhead round $r: $label"
            if [ "$label" = agent-on ]; then up "$AGENT"; else up ""; fi
            step "run_overhead ($label)" $LOAD demo/run_overhead.sh "$NAME/overhead" "$label"
        done
    done
fi

# ---- 3. open-loop saturation ----------------------------------------------------------------
if ! skipped openloop; then
    TSV=$OUT/openloop.tsv
    printf 'label\tendpoint\ttarget_rps\trequests\terrors\tp50_ms\tp95_ms\tp99_ms\trps\tcpu_ms_per_req\tlate_starts\terror_kinds\tsyn_retrans\tlisten_overflows\tlisten_drops\tsteal_pct\n' > "$TSV"
    # The load generator runs in a container on the compose network and calls the frontend
    # directly, not through the published port and Docker's userland proxy on the machine.
    loadgen() {
        sudo docker run --rm --network "$NET" --cpuset-cpus "$LOAD_CPUS" \
            --sysctl net.ipv4.ip_local_port_range="1024 65535" --sysctl net.ipv4.tcp_tw_reuse=1 \
            -v "$PWD/demo:/demo:ro" "$LOADGEN_IMAGE" python3 /demo/loadgen.py "$@"
    }
    # ponytail: labels always run off then on, rates ascending; alternate the order if drift shows up
    for label in agent-off agent-on; do
        if [ "$label" = agent-on ]; then up "$AGENT"; else up ""; fi
        pid=$(frontend_pid)
        NET=$(sudo docker network ls --format '{{.Name}}' | grep -m1 '_expnet$')   # exists only once the stack is up
        # By IP: a name would be resolved through Docker's DNS on every request.
        FRONT=http://$(cd demo && sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$(sudo docker compose ps -q frontend)"):8080/direct
        loadgen "$FRONT" --requests "$WARMUP" --concurrency "$CONCURRENCY" --warmup 0 > /dev/null
        for rate in $RATES; do
            log "open loop: $label /direct at $rate req/s"
            t0=$(cpu_ticks "$pid"); s0=$(steal_total); d0=$(listen_drops "$pid")
            json=$(loadgen "$FRONT" --rate "$rate" --duration "$DURATION" --procs "$LOAD_PROCS")
            t1=$(cpu_ticks "$pid"); s1=$(steal_total); d1=$(listen_drops "$pid")
            if [ -z "$json" ]; then log "WARNING: load generator returned nothing at $label $rate req/s"; continue; fi
            diag=$(awk -v s0="$s0" -v s1="$s1" -v d0="$d0" -v d1="$d1" 'BEGIN {
                split(s0, a, " "); split(s1, b, " "); split(d0, c, " "); split(d1, d, " ")
                printf "%d\t%d\t%.2f", d[1] - c[1], d[2] - c[2], (b[2] > a[2]) ? 100 * (b[1] - a[1]) / (b[2] - a[2]) : 0 }')
            printf '%s' "$json" | python3 -c 'import json, sys
d = json.load(sys.stdin); label, rate, ticks, hz, diag = sys.argv[1:]
ok = d["requests"] - d["errors"]
cpu = (int(ticks) / int(hz)) * 1000 / ok if ok else 0
kinds = ",".join(f"{k}:{n}" for k, n in d.get("error_kinds", {}).items()) or "-"
print("\t".join(str(v) for v in [label, "direct", rate, d["requests"], d["errors"], d["p50_ms"], d["p95_ms"], d["p99_ms"], d["rps"], round(cpu, 3), d["late_starts"], kinds, d.get("syn_retrans", "-")]) + "\t" + diag)' \
                "$label" "$rate" "$((t1 - t0))" "$(getconf CLK_TCK)" "$diag" >> "$TSV"
            sleep "$STEP_GAP"   # let the step's TIME_WAIT sockets expire before the next one
        done
    done
fi

compose down > /dev/null 2>&1
rm -f demo/docker-compose.pin.yml
python3 vm/summarize.py "$OUT" | tee "$OUT/summary.md"
echo "load average at end: $(cat /proc/loadavg)" >> "$OUT/env.txt"
tar -czf "$OUT.tar.gz" --exclude="jaeger_*.json" -C demo "$NAME"
log "done: $OUT/summary.md, archive $OUT.tar.gz (raw Jaeger JSON stays in $OUT)"
