#!/bin/bash
# Runs the whole measurement suite on a dedicated machine (meant for a VM with nothing else on it)
# and packs the results with a description of the environment.
#
#   1. correctness: sequential and concurrent load on Netty NIO, Netty epoll and CIO, agent on
#   2. closed-loop overhead: run_overhead.sh, agent off / on, ROUNDS rounds in alternating order
#   3. open-loop saturation: fixed arrival rates, agent off / on, JVM CPU per request
#
# Usage: vm/measure.sh [results-name]      (results land in demo/<results-name>, default results-vm-<time>)
# Env:   ROUNDS=5 REQUESTS=4000 CONCURRENCY=16 WARMUP=300
#        RATES="300 600 900 1200 1500" DURATION=20
#        PIN=auto|0|1   split CPUs between frontend, backend/jaeger and the load generator
#        SKIP=correctness,overhead,openloop   comma-separated phases to skip
set -u
cd "$(dirname "$0")/.."
NAME=${1:-results-vm-$(date +%Y%m%d-%H%M%S)}
OUT=demo/$NAME
ROUNDS=${ROUNDS:-5}
RATES=${RATES:-300 600 900 1200 1500}
DURATION=${DURATION:-20}
SKIP=${SKIP:-}
export REQUESTS=${REQUESTS:-4000} CONCURRENCY=${CONCURRENCY:-16} WARMUP=${WARMUP:-300}
AGENT="-javaagent:/coroagent/coroagent.jar -Dobicoro.native=/coroagent/libcoroagent.so"
mkdir -p "$OUT"
log() { echo "[measure $(date +%H:%M:%S)] $*" | tee -a "$OUT/measure.log"; }
skipped() { [[ ",$SKIP," == *",$1,"* ]]; }

# ---- CPU pinning ----------------------------------------------------------------------------
N=$(nproc)
PIN=${PIN:-auto}
[ "$PIN" = auto ] && { [ "$N" -ge 8 ] && PIN=1 || PIN=0; }
LOAD_CPUS=0-$((N - 1))
if [ "$PIN" = 1 ]; then
    F=$((N / 2)); B=$((N / 4))
    FRONT_CPUS=0-$((F - 1)); BACK_CPUS=$F-$((F + B - 1)); LOAD_CPUS=$((F + B))-$((N - 1))
    cat > demo/docker-compose.pin.yml <<EOF
# Generated by vm/measure.sh: keeps the services and the load generator off each other's CPUs.
services:
  frontend: { cpuset: "$FRONT_CPUS" }
  backend:  { cpuset: "$BACK_CPUS" }
  jfront:   { cpuset: "$BACK_CPUS" }
  jaeger:   { cpuset: "$BACK_CPUS" }
EOF
    export COMPOSE_FILE=docker-compose.yml:docker-compose.pin.yml
    log "pinning: frontend $FRONT_CPUS, backend/jaeger $BACK_CPUS, load generator $LOAD_CPUS (of $N)"
else
    log "pinning off ($N CPUs)"
fi
LOAD="taskset -c $LOAD_CPUS"

# ---- environment ----------------------------------------------------------------------------
{
    echo "# measure.sh run $NAME"
    echo "date: $(date -Is)"; echo "git: $(git rev-parse --short HEAD) $(git status --porcelain | wc -l) dirty files"
    echo "kernel: $(uname -r)"; echo "btf: $(ls /sys/kernel/btf/vmlinux 2>&1)"
    echo "cpus: $N, pin=$PIN load=$LOAD_CPUS"; lscpu | grep -E 'Model name|Hypervisor|Thread|Core|Socket|MHz' || true
    free -h | head -2
    echo "docker: $(docker --version 2>&1)"; echo "java: $(java -version 2>&1 | head -1)"
    echo "bpftrace: $(${BPFTRACE:-bpftrace} --version 2>&1)"
    echo "load average at start: $(cat /proc/loadavg)"
    echo "busiest processes at start:"; top -b -n1 -o %CPU | sed -n 7,12p
    echo "config: ROUNDS=$ROUNDS REQUESTS=$REQUESTS CONCURRENCY=$CONCURRENCY WARMUP=$WARMUP RATES=\"$RATES\" DURATION=$DURATION"
} > "$OUT/env.txt"

compose() { (cd demo && sudo -E docker compose "$@"); }
up() {  # <java opts> [extra env assignments...]
    local opts=$1; shift
    compose down > /dev/null 2>&1
    (cd demo && env "$@" FRONTEND_JAVA_OPTS="$opts" sudo -E docker compose up -d > /dev/null 2>&1)
    sleep 25
    for _ in 1 2 3; do for ep in direct hop parallel; do curl -s -m 10 -o /dev/null "http://localhost:8080/$ep"; done; done
    sleep 5
}
frontend_pid() { (cd demo && sudo docker inspect -f '{{.State.Pid}}' "$(sudo docker compose ps -q frontend)"); }
cpu_ticks() { sudo awk '{ sub(/^.*\) /, ""); print $12 + $13 }' "/proc/$1/stat"; }

# ---- 1. correctness -------------------------------------------------------------------------
if ! skipped correctness; then
    for variant in nio epoll cio; do
        case $variant in nio) extra=();; epoll) extra=(NETTY_TRANSPORT=epoll);; cio) extra=(KTOR_ENGINE=cio);; esac
        log "correctness: $variant"
        up "$AGENT" "${extra[@]}"
        $LOAD demo/run_conditions.sh "$NAME/seq-$variant" > /dev/null 2>&1
        python3 demo/analyze_jaeger.py "$NAME/seq-$variant" > "$OUT/seq-$variant/analysis.txt"
        $LOAD demo/run_concurrent.sh "$NAME/conc-$variant" > /dev/null 2>&1
        python3 demo/analyze_concurrent.py "$NAME/conc-$variant" > "$OUT/conc-$variant/analysis.txt"
        compose logs --no-color frontend 2>&1 | grep -c 'transform error' | sed 's/^/transform errors: /' >> "$OUT/conc-$variant/analysis.txt"
    done
fi

# ---- 2. closed-loop overhead ----------------------------------------------------------------
if ! skipped overhead; then
    for r in $(seq 1 "$ROUNDS"); do
        order="agent-off agent-on"; [ $((r % 2)) = 0 ] && order="agent-on agent-off"
        for label in $order; do
            log "overhead round $r: $label"
            if [ "$label" = agent-on ]; then up "$AGENT"; else up ""; fi
            $LOAD demo/run_overhead.sh "$NAME/overhead" "$label" > /dev/null 2>> "$OUT/measure.log"
        done
    done
fi

# ---- 3. open-loop saturation ----------------------------------------------------------------
if ! skipped openloop; then
    TSV=$OUT/openloop.tsv
    printf 'label\tendpoint\ttarget_rps\trequests\terrors\tp50_ms\tp95_ms\tp99_ms\trps\tcpu_ms_per_req\n' > "$TSV"
    for label in agent-off agent-on; do
        if [ "$label" = agent-on ]; then up "$AGENT"; else up ""; fi
        pid=$(frontend_pid)
        for rate in $RATES; do
            log "open loop: $label /direct at $rate req/s"
            t0=$(cpu_ticks "$pid")
            json=$($LOAD python3 demo/loadgen.py http://localhost:8080/direct --rate "$rate" --duration "$DURATION")
            t1=$(cpu_ticks "$pid")
            printf '%s' "$json" | python3 -c 'import json, sys
d = json.load(sys.stdin); label, rate, ticks, hz = sys.argv[1:]
ok = d["requests"] - d["errors"]
cpu = (int(ticks) / int(hz)) * 1000 / ok if ok else 0
print("\t".join(str(v) for v in [label, "direct", rate, d["requests"], d["errors"], d["p50_ms"], d["p95_ms"], d["p99_ms"], d["rps"], round(cpu, 3)]))' \
                "$label" "$rate" "$((t1 - t0))" "$(getconf CLK_TCK)" >> "$TSV"
            sleep 5
        done
    done
fi

compose down > /dev/null 2>&1
rm -f demo/docker-compose.pin.yml
python3 vm/summarize.py "$OUT" | tee "$OUT/summary.md"
echo "load average at end: $(cat /proc/loadavg)" >> "$OUT/env.txt"
tar -czf "$OUT.tar.gz" --exclude="jaeger_*.json" -C demo "$NAME"
log "done: $OUT/summary.md, archive $OUT.tar.gz (raw Jaeger JSON stays in $OUT)"
